# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/saurabh/Persistent/Project/OnlineVotingSystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/saurabh/Persistent/Project/OnlineVotingSystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saurabh/Persistent/Project/OnlineVotingSystem/CMakeFiles /home/saurabh/Persistent/Project/OnlineVotingSystem/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saurabh/Persistent/Project/OnlineVotingSystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cmakeexecutable

# Build rule for target.
cmakeexecutable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmakeexecutable
.PHONY : cmakeexecutable

# fast build rule for target.
cmakeexecutable/fast:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/build
.PHONY : cmakeexecutable/fast

Candidate.o: Candidate.cpp.o

.PHONY : Candidate.o

# target to build an object file
Candidate.cpp.o:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Candidate.cpp.o
.PHONY : Candidate.cpp.o

Candidate.i: Candidate.cpp.i

.PHONY : Candidate.i

# target to preprocess a source file
Candidate.cpp.i:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Candidate.cpp.i
.PHONY : Candidate.cpp.i

Candidate.s: Candidate.cpp.s

.PHONY : Candidate.s

# target to generate assembly for a file
Candidate.cpp.s:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Candidate.cpp.s
.PHONY : Candidate.cpp.s

Election.o: Election.cpp.o

.PHONY : Election.o

# target to build an object file
Election.cpp.o:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Election.cpp.o
.PHONY : Election.cpp.o

Election.i: Election.cpp.i

.PHONY : Election.i

# target to preprocess a source file
Election.cpp.i:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Election.cpp.i
.PHONY : Election.cpp.i

Election.s: Election.cpp.s

.PHONY : Election.s

# target to generate assembly for a file
Election.cpp.s:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Election.cpp.s
.PHONY : Election.cpp.s

ElectionComission.o: ElectionComission.cpp.o

.PHONY : ElectionComission.o

# target to build an object file
ElectionComission.cpp.o:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/ElectionComission.cpp.o
.PHONY : ElectionComission.cpp.o

ElectionComission.i: ElectionComission.cpp.i

.PHONY : ElectionComission.i

# target to preprocess a source file
ElectionComission.cpp.i:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/ElectionComission.cpp.i
.PHONY : ElectionComission.cpp.i

ElectionComission.s: ElectionComission.cpp.s

.PHONY : ElectionComission.s

# target to generate assembly for a file
ElectionComission.cpp.s:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/ElectionComission.cpp.s
.PHONY : ElectionComission.cpp.s

Person.o: Person.cpp.o

.PHONY : Person.o

# target to build an object file
Person.cpp.o:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Person.cpp.o
.PHONY : Person.cpp.o

Person.i: Person.cpp.i

.PHONY : Person.i

# target to preprocess a source file
Person.cpp.i:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Person.cpp.i
.PHONY : Person.cpp.i

Person.s: Person.cpp.s

.PHONY : Person.s

# target to generate assembly for a file
Person.cpp.s:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Person.cpp.s
.PHONY : Person.cpp.s

State.o: State.cpp.o

.PHONY : State.o

# target to build an object file
State.cpp.o:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/State.cpp.o
.PHONY : State.cpp.o

State.i: State.cpp.i

.PHONY : State.i

# target to preprocess a source file
State.cpp.i:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/State.cpp.i
.PHONY : State.cpp.i

State.s: State.cpp.s

.PHONY : State.s

# target to generate assembly for a file
State.cpp.s:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/State.cpp.s
.PHONY : State.cpp.s

Voter.o: Voter.cpp.o

.PHONY : Voter.o

# target to build an object file
Voter.cpp.o:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Voter.cpp.o
.PHONY : Voter.cpp.o

Voter.i: Voter.cpp.i

.PHONY : Voter.i

# target to preprocess a source file
Voter.cpp.i:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Voter.cpp.i
.PHONY : Voter.cpp.i

Voter.s: Voter.cpp.s

.PHONY : Voter.s

# target to generate assembly for a file
Voter.cpp.s:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/Voter.cpp.s
.PHONY : Voter.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/cmakeexecutable.dir/build.make CMakeFiles/cmakeexecutable.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... cmakeexecutable"
	@echo "... edit_cache"
	@echo "... Candidate.o"
	@echo "... Candidate.i"
	@echo "... Candidate.s"
	@echo "... Election.o"
	@echo "... Election.i"
	@echo "... Election.s"
	@echo "... ElectionComission.o"
	@echo "... ElectionComission.i"
	@echo "... ElectionComission.s"
	@echo "... Person.o"
	@echo "... Person.i"
	@echo "... Person.s"
	@echo "... State.o"
	@echo "... State.i"
	@echo "... State.s"
	@echo "... Voter.o"
	@echo "... Voter.i"
	@echo "... Voter.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

